name: Build and push Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Build docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: shadowless/auto-mailer
          tag_with_ref: true